export 'action_search_object.dart' show actionSearchObject;
export 'string_to_array.dart' show stringToArray;
export 'get_current_page.dart' show getCurrentPage;
export 'get_week_days_json.dart' show getWeekDaysJson;
export 'get_day_json.dart' show getDayJson;
export 'validate_cpf_cnpj.dart' show validateCpfCnpj;
export 'validate_data.dart' show validateData;
export 'custom_navigation.dart' show customNavigation;
export 'get_actual_page_name.dart' show getActualPageName;
